# Generated by Django 4.2.17 on 2024-12-16 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='numbers',
            name='request_last_request',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
